
configuration : configuration.c tst_configuration.c configuration.h
	gcc -c configuration.c
	gcc -c tst_configuration.c
	gcc -o config.out configuration.o tst_configuration.o
	./config.out


clean : 
	rm -f prog *.o 
	rm -f prog *.out
